### ISSUE TITLE
Ensure HBM resource creation logic is idempotent

### ISSUE THREAD

**Issue by anders-larsson** [kodguru/puppet-module-hbm#3]
Currently the HBM module creating resources every Puppet run due to a bug(?) in the code. I suspect the fault is in lib/puppet/provider/hbm.rb but I could be wrong.

We need to fix this to ensure the module is idempotent.

**Comment by Phil-Friderici** [comment]
v0.3.7 should fix this issue. Please verify and confirm.

**Comment by anders-larsson** [comment]
I can confirm this is the case. Sorry, must have missed this comment. Closing!
